const AllProducts = [
    // PICO
    {
        product_No: 1,
        product_img1: "img/VR HEADSET/Pico4-128GB.png",
        product_img2: "img/VR HEADSET/Pico4-128GB-2.png",
        product_img3: "img/VR HEADSET/Pico4-128GB-3.png",
        product_name: "Pico4-128GB All-in-One VR Headset",
        product_desc1: "Resolution: 4320 x 2160 Px",
        product_desc2: "Field of view: 105°",
        product_desc3: "Refresh rate: up to 90 Hz",
        product_desc4: "incl. 16MP RGB front camera",
        product_price: "$ 389.00",
        product_deltime: "Delivery time 1-2 weeks",
    },
    {
        product_No: 2,
        product_img1: "img/VR HEADSET/Pico4-128GB.png",
        product_img2: "img/VR HEADSET/Pico4-128GB-2.png",
        product_img3: "img/VR HEADSET/Pico4-128GB-3.png",
        product_name: "Pico 4 (256 GB) All-in-One VR-Headset",
        product_desc1: "Resolution: 4320 x 2160 Px",
        product_desc2: "Field of view: 105°",
        product_desc3: "Refresh rate: up to 90 Hz",
        product_desc4: "incl. 16MP RGB front camera",
        product_price: "$ 458.99",
        product_deltime: "Delivery time 1-2 weeks",
    },
    {
        product_No: 3,
        product_img1: "img/VR HEADSET/PicoNeo3pro-2.png",
        product_img2: "img/VR HEADSET/PicoNeo3pro-1.png",
        product_img3: "img/VR HEADSET/PicoNeo3pro-3.png",
        product_name: "Pico 4 Enterprise (256 GB) All-in-One",
        product_desc1: " Resolution: 4320 x 2160 Px",
        product_desc2: "Field of view: 105°",
        product_desc3: "incl. face & eye tracking plus automatic IPD",
        product_desc4: "incl. 16 MP RGB front camera",
        product_price: "$1,069.00",
        product_deltime:"Delivery time 3-5 days",
    },
    {
        product_No: 4,
        product_img1: "img/VR HEADSET/PicoG30-1.png",
        product_img2: "img/VR HEADSET/PicoG30-2.png",
        product_img3: "img/VR HEADSET/PicoG30-3.png",
        product_name: "PICO G3 3 DoF Standalone",
        product_desc1: "Resolution: 3664 x 1920",
        product_desc2: "Refresh rate: 90 Hz",
        product_desc3: "Battery time: bis zu 3 Stunden",
        product_desc4: "Storage: 128 GB",
        product_price: "$ 469.00",
        product_deltime:"Delivery time 3-5 days",
    },
    // VARJO
    {
        product_No: 5,
        product_img1: "img/VR HEADSET/VarjoVR3-1.png",
        product_img2: "img/VR HEADSET/VarjoVR3-2.png",
        product_img3: "img/VR HEADSET/VarjoVR3-3.png",
        product_name: "Varjo VR-3 High-end VR-Headset",
        product_desc1: "Full Frame Bionic Display™ and 200 Hz Eye-Tracking",
        product_desc2: "Pixel Density: 70 PPD",
        product_desc3: "incl. integrated UltraLeap Hand Tracking",
        product_desc4: "Varjo Subscription not included (sold separately)",
        product_price: "$4,299.01",
        product_deltime:"Delivery time 7-10 days",
    },
    {
        product_No: 6,
        product_img1: "img/VR HEADSET/VarjoXR3-1.png",
        product_img2: "img/VR HEADSET/VarjoXR3-2.png",
        product_img3: "img/VR HEADSET/VarjoXR3-3.png",
        product_name: "Varjo XR-3 Mixed-Reality-Headset",
        product_desc1: "True-to-Life Mixed-Reality via Video pass-through",
        product_desc2: "Integrated Hand und Eye Tracking (200 Hz)",
        product_desc3: " incl. Varjo Inside-out Tracking",
        product_desc4: "Varjo Subscription not included (sold separately)",
        product_price: "$ 7,729.00",
        product_deltime:"Delivery time 7-10 days",
    },
    {
        product_No: 7,
        product_img1: "img/VR HEADSET/VarjoXR4-1.png",
        product_img2: "img/VR HEADSET/VarjoXR4-2.png",
        product_img3: "img/VR HEADSET/VarjoXR4-3.png",
        product_name: "Varjo XR-4 High-end Mixed Reality Headset",
        product_desc1: "Resolution: 3840x3744 per Eye (51 PPD)",
        product_desc2: "Field of View: 120° x 105°",
        product_desc3: "Refresh Rate: 90 Hz",
        product_desc4: "incl. AutoIPD, Varjo Inside-out- & Eye Tracking",
        product_price: "$ 4,749.00",
        product_deltime:"Delivery time 3-5 days",
    },
    {
        product_No: 8,
        product_img1: "img/VR HEADSET/VarjoXR4Stream-1.png",
        product_img2: "img/VR HEADSET/VarjoXR4Stream-2.png",
        product_img3: "img/VR HEADSET/VarjoXR4Stream-3.png",
        product_name: "Varjo XR-4 (SteamVR Tracking) High-end",
        product_desc1: " Resolution: 3840 x 3744 per eye (51 PPD)",
        product_desc2: " Field of View: 120° x 105°",
        product_desc3: "Refresh Rate: 90 Hz",
        product_desc4: " Includes Auto IPD, SteamVR & Eye Tracking",
        product_price: "€5,998.99",
        product_deltime:"Delivery time 3-5 days",
    },
     // META
    {
        product_No: 9,
        product_img1: "img/VR HEADSET/MetaQuest3-1.png",
        product_img2: "img/VR HEADSET/MetaQuest3-2.png",
        product_img3: "img/VR HEADSET/MetaEliteStrapBat-3.png",
        product_name: "Meta Quest 3 (128 GB) Enterprise",
        product_desc1: "Resolution: 4.128 x 2.208",
        product_desc2: "Refresh rate: 120 Hz",
        product_desc3: " Powerful XR2 Gen 2 chip with 8 GB RAM",
        product_desc4: "Ultra-light pancake lenses & stereo passthrough",
        product_price: "$ 549.99",
        product_deltime:"Delivery time 3-5 Days",
    },
    {
        product_No: 10,
        product_img1: "img/VR HEADSET/MetaQuest3-1.png",
        product_img2: "img/VR HEADSET/MetaQuest3-2.png",
        product_img3: "img/VR HEADSET/MetaEliteStrapBat-3.png",
        product_name: "Meta Quest 3 (512 GB) Enterprise",
        product_desc1: "Resolution: 4.128 x 2.208",
        product_desc2: "Refresh rate: 120 Hz",
        product_desc3: " Powerful XR2 Gen 2 chip with 8 GB RAM",
        product_desc4: "Ultra-light pancake lenses & stereo passthrough",
        product_price: "$ 699.99",
        product_deltime:"Delivery time 3-5 Days",
    },
    {
        product_No: 11,
        product_img1: "img/VR HEADSET/MetaQuestPro-1.png",
        product_img2: "img/VR HEADSET/MetaQuestPro-2.png",
        product_img3: "img/VR HEADSET/MetaQuestPro-3.png",
        product_name: "Meta Quest Pro (Enterprise)",
        product_desc1: "Resolution: 1.800 x 1.920 per eye",
        product_desc2: "Field of view: 106°",
        product_desc3: "incl. face, eye & hand tracking",
        product_desc4: "supports WiFi 6E",
        product_price: "$ 1,199.00",
        product_deltime:"Delivery time 3-5 Days",
    },
    {
        product_No: 12,
        product_img1: "img/VR HEADSET/MetaEliteStrapBat-1.png",
        product_img2: "img/VR HEADSET/MetaEliteStrapBat-2.png",
        product_img3: "img/VR HEADSET/MetaEliteStrapBat-3.png",
        product_name: "Meta Quest 3 - Elite strap (with battery)",
        product_desc1: "adjustable headset Strap",
        product_desc2: "Battery, up to 2hrs, 2330mAh",
        product_desc3: "Durable Materials",
        product_desc4: "Rotary Knob precise adjustment",
        product_price: "$ 149.99",
        product_deltime:"Delivery time 5-7 days",
    },
];

// // Convert the array to a JSON string
// const productsJSON = JSON.stringify(AllProducts);

// // Store the JSON string in local storage
// localStorage.setItem('products', productsJSON);

let cartProducts = [];
if(localStorage.getItem("products_cart")){
    cartProducts = JSON.parse(localStorage.getItem("products_cart"));
};
